# -*- coding: utf-8 -*-
"""Copy of Text Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQdGePKnc64cWnKdgMikR0byo0pLH_iY
"""

pip install transforms torch

from transformers import pipeline
# Load text generation model (GenAI)
generator = pipeline(
    "text-generation",
    model="gpt2"
)
# Input prompt
promt = "Artificial Intelligence in finance will"
result = generator(prompt,max_length=50,num_return_sequence=1)
print("AI Generated Text:")
print(result[0]['generated_text'])